<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyPhongNet" Class="DataPhongNetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-K3FKG32;Initial Catalog=QuanLyPhongNet;Integrated Security=True" SettingsObjectName="Nhom3DoAn_Remake.Properties.Settings" SettingsPropertyName="QuanLyPhongNetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="TIEN" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.THUCAN" Member="THUCANs">
    <Type Name="THUCAN">
      <Column Name="MA" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GIA" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.THUCUONG" Member="THUCUONGs">
    <Type Name="THUCUONG">
      <Column Name="MA" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GIA" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MAY" Member="MAYs">
    <Type Name="MAY">
      <Column Name="MAY" Member="MAY1" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LOAI" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIA" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>